services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest@sha256:7bb6963b730df6a1070f7a08a607b0eb7a87fe65abfa4742d876ad33bb1267eb
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    environment:
      - TZ=Asia/Tokyo
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1
    ports:
      - "127.0.0.1:5050:5000"
    restart: unless-stopped
    depends_on:
      playwright-chrome:
        condition: service_started

  playwright-chrome:
    image: ghcr.io/browserless/chromium@sha256:ae07025606e03c9b263620aaf4d09c52728f71a104ac7d471a68c23dec72c05f
    container_name: playwright-chrome
    hostname: playwright-chrome
    environment:
      - TIMEOUT=600000
      - CONCURRENT=10
    restart: unless-stopped

volumes:
  changedetection-data:
